import { clamp, el, fmtTime } from "./audio_editor_core.js";

export class WaveformView {
  constructor(container,onSelection){this.container=container;this.onSelection=onSelection;this.cache=new Map();this.audio=new Audio();this.audio.preload="auto";this.url="";this.decoded=null;this.zoom=28;this.duration=1;this.selection=null;this.sections=[];this.raf=null;this.build();}
  build(){this.root=el("div","m3ssv2-wave-root");this.scroll=el("div","m3ssv2-wave-scroll");this.stage=el("div","m3ssv2-wave-stage");this.canvas=document.createElement("canvas");this.canvas.className="m3ssv2-wave-canvas";this.sectionLayer=el("div","m3ssv2-semantic-overlay");this.selectionEl=el("div","m3ssv2-wave-selection");this.playhead=el("div","m3ssv2-playhead");this.stage.append(this.canvas,this.sectionLayer,this.selectionEl,this.playhead);this.scroll.appendChild(this.stage);this.root.appendChild(this.scroll);this.container.appendChild(this.root);let drag=null;this.stage.addEventListener("pointerdown",e=>{if(e.button!==0)return;const r=this.stage.getBoundingClientRect();drag=clamp((e.clientX-r.left)/r.width*this.duration,0,this.duration);this.stage.setPointerCapture?.(e.pointerId);this.setSelection({start:drag,end:drag});});this.stage.addEventListener("pointermove",e=>{if(drag===null)return;const r=this.stage.getBoundingClientRect(),now=clamp((e.clientX-r.left)/r.width*this.duration,0,this.duration);this.setSelection({start:Math.min(drag,now),end:Math.max(drag,now)});});const done=e=>{if(drag===null)return;this.stage.releasePointerCapture?.(e.pointerId);if(this.selection&&Math.abs(this.selection.end-this.selection.start)<.02){this.audio.currentTime=this.selection.start;this.setSelection(null);}drag=null;};this.stage.addEventListener("pointerup",done);this.stage.addEventListener("pointercancel",done);this.audio.addEventListener("timeupdate",()=>this.updatePlayhead());this.audio.addEventListener("ended",()=>this.stopAnimation());}
  destroy(){this.stopAnimation();this.audio.pause();this.audio.src="";}
  async setSource(url){if(!url)return;this.url=url;this.audio.src=url;let decoded=this.cache.get(url);if(!decoded){const res=await fetch(url);if(!res.ok)throw new Error(`Audio preview request failed: ${res.status}`);const bytes=await res.arrayBuffer(),ctx=new (window.AudioContext||window.webkitAudioContext)();try{decoded=await ctx.decodeAudioData(bytes.slice(0));}finally{await ctx.close();}this.cache.set(url,decoded);}if(this.url!==url)return;this.decoded=decoded;this.duration=decoded.duration||1;this.selection=null;this.render();}
  setZoom(x){this.zoom=clamp(x,8,120);this.render();} setSemanticSections(x){this.sections=x||[];this.renderSections();}
  render(){const width=Math.min(40000,Math.max(this.scroll.clientWidth||900,Math.round(this.duration*this.zoom))),h=180,dpr=Math.min(devicePixelRatio||1,2);this.stage.style.width=`${width}px`;this.stage.style.height=`${h}px`;this.canvas.width=Math.round(width*dpr);this.canvas.height=Math.round(h*dpr);this.canvas.style.width=`${width}px`;this.canvas.style.height=`${h}px`;const c=this.canvas.getContext("2d");c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle="#0b0f18";c.fillRect(0,0,width,h);const step=this.duration>180?30:this.duration>60?10:5;c.font="10px ui-monospace,monospace";for(let t=0;t<=this.duration;t+=step){const x=t/this.duration*width;c.strokeStyle="rgba(255,255,255,.07)";c.beginPath();c.moveTo(x+.5,0);c.lineTo(x+.5,h);c.stroke();c.fillStyle="rgba(255,255,255,.42)";c.fillText(fmtTime(t),x+4,h-6);}if(this.decoded){const len=this.decoded.length,half=h/2;c.strokeStyle="rgba(92,210,190,.9)";c.beginPath();for(let x=0;x<width;x++){const a=Math.floor(x/width*len),b=Math.max(a+1,Math.floor((x+1)/width*len));let lo=1,hi=-1;for(let ch=0;ch<this.decoded.numberOfChannels;ch++){const d=this.decoded.getChannelData(ch),stride=Math.max(1,Math.floor((b-a)/8));for(let i=a;i<b;i+=stride){const v=d[i]||0;lo=Math.min(lo,v);hi=Math.max(hi,v);}}c.moveTo(x+.5,half-hi*half*.86);c.lineTo(x+.5,half-lo*half*.86);}c.stroke();}this.renderSections();this.updateSelection();this.updatePlayhead();}
  renderSections(){if(!this.sectionLayer)return;this.sectionLayer.replaceChildren();for(const s of this.sections){const a=clamp(s.start/this.duration*100,0,100),b=clamp(s.end/this.duration*100,0,100);if(b<=a)continue;const x=el("div","m3ssv2-semantic-section",s.label);x.style.left=`${a}%`;x.style.width=`${Math.max(.2,b-a)}%`;x.title=`${s.label} · ${fmtTime(s.start)}–${fmtTime(s.end)}`;this.sectionLayer.appendChild(x);}}
  setSelection(s){this.selection=s;this.updateSelection();this.onSelection?.(s);} updateSelection(){if(!this.selection){this.selectionEl.style.display="none";return;}this.selectionEl.style.display="block";this.selectionEl.style.left=`${this.selection.start/this.duration*100}%`;this.selectionEl.style.width=`${Math.max(.1,(this.selection.end-this.selection.start)/this.duration*100)}%`;}
  currentTime(){return Number(this.audio.currentTime)||0;} play(){this.audio.play();this.startAnimation();} pause(){this.audio.pause();this.stopAnimation();this.updatePlayhead();} stop(){this.audio.pause();this.audio.currentTime=0;this.stopAnimation();this.updatePlayhead();}
  startAnimation(){this.stopAnimation();const tick=()=>{this.updatePlayhead();if(!this.audio.paused)this.raf=requestAnimationFrame(tick);};this.raf=requestAnimationFrame(tick);} stopAnimation(){if(this.raf)cancelAnimationFrame(this.raf);this.raf=null;} updatePlayhead(){this.playhead.style.left=`${clamp(this.currentTime()/Math.max(this.duration,.001)*100,0,100)}%`;}
}
