import { CHANNEL_MODES, FADE_CURVES, clamp, clipDuration, el, field, input, select } from "./audio_editor_core.js";

function change(control,event,commit,fn){control.addEventListener(event,()=>commit(()=>fn(control)));return control;}
export function renderInspector(container, clip, meta, commit) {
  container.replaceChildren();if(!clip){container.appendChild(el("div","m3ssv2-empty","Select a clip to edit its properties."));return;}
  const sources=(meta?.takes||[]).map(t=>({value:t.id,label:t.name||t.id})),grid=el("div","m3ssv2-grid m3ssv2-grid-2");
  const source=select(sources,clip.source_id);change(source,"change",commit,x=>{const old=clipDuration(clip),take=meta.takes.find(t=>t.id===x.value),max=Number(take?.duration)||old;clip.source_id=x.value;clip.source_in=clamp(clip.source_in,0,max);clip.source_out=clamp(clip.source_in+old,clip.source_in+.01,max);});grid.appendChild(field("Source take",source));
  for(const [key,label,min,max,step] of [["source_in","Source in (s)",0,3600,.01],["source_out","Source out (s)",0,3600,.01],["timeline_start","Timeline start (s)",0,3600,.01],["gain_db","Gain (dB)",-60,24,.1],["pan","Pan",-1,1,.01]]){const c=input("number",clip[key],min,max,step);change(c,"change",commit,x=>clip[key]=clamp(x.value,min,max));grid.appendChild(field(label,c));}
  const fi=input("number",clip.fade_in?.duration||0,0,clipDuration(clip),.01),fo=input("number",clip.fade_out?.duration||0,0,clipDuration(clip),.01),curve=select(FADE_CURVES,clip.fade_in?.curve||"linear");change(fi,"change",commit,x=>clip.fade_in.duration=clamp(x.value,0,clipDuration(clip)));change(fo,"change",commit,x=>clip.fade_out.duration=clamp(x.value,0,clipDuration(clip)));change(curve,"change",commit,x=>{clip.fade_in.curve=x.value;clip.fade_out.curve=x.value;});grid.append(field("Fade in (s)",fi),field("Fade out (s)",fo),field("Fade curve",curve));
  const rev=input("checkbox");rev.checked=!!clip.reverse;change(rev,"change",commit,x=>clip.reverse=x.checked);const mute=input("checkbox");mute.checked=!!clip.muted;change(mute,"change",commit,x=>clip.muted=x.checked);grid.append(field("Reverse",rev),field("Muted",mute));container.appendChild(grid);
}

export function renderEnvelope(container, clip, commit, begin, refresh) {
  container.replaceChildren();if(!clip){container.appendChild(el("div","m3ssv2-empty","Select a clip to edit its gain envelope."));return;}
  container.appendChild(el("div","m3ssv2-envelope-note","Selected clip Gain Envelope · time is relative to this clip · backend anchors 0 dB at clip start/end. Use the toolbar Envelope toggle to show/hide the same curve over the rendered waveform."));
  const wrap=el("div","m3ssv2-envelope-wrap"),canvas=document.createElement("canvas");canvas.className="m3ssv2-envelope";wrap.appendChild(canvas);container.appendChild(wrap);const pts=clip.gain_envelope||(clip.gain_envelope=[]),dur=Math.max(.01,clipDuration(clip));let dragPoint=null;
  function resize(){const r=wrap.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(400,Math.round(r.width*dpr));canvas.height=240*dpr;canvas.style.height="240px";draw();}
  function xy(p,w,h){return [p.time/dur*w,(12-clamp(p.gain_db,-60,12))/72*h];}
  function previewPoints(){const map=new Map();for(const p of [{time:0,gain_db:0},...pts,{time:dur,gain_db:0}])map.set(clamp(p.time,0,dur).toFixed(6),{time:clamp(p.time,0,dur),gain_db:clamp(p.gain_db,-60,12)});return [...map.values()].sort((a,b)=>a.time-b.time);}
  function draw(){const dpr=Math.min(devicePixelRatio||1,2),w=canvas.width/dpr,h=canvas.height/dpr,c=canvas.getContext("2d");c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle="#0b0f18";c.fillRect(0,0,w,h);c.strokeStyle="rgba(255,255,255,.08)";for(const db of [12,0,-12,-24,-36,-48,-60]){const y=(12-db)/72*h;c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();c.fillStyle="rgba(255,255,255,.5)";c.fillText(`${db} dB`,5,y-3);}const sorted=previewPoints();c.strokeStyle="#5cd2be";c.lineWidth=2;c.beginPath();let first=true;for(const p of sorted){const [x,y]=xy(p,w,h);if(first){c.moveTo(x,y);first=false;}else c.lineTo(x,y);}c.stroke();for(const p of pts){const [x,y]=xy(p,w,h);c.fillStyle="#78a6ff";c.beginPath();c.arc(x,y,5,0,Math.PI*2);c.fill();}}
  function point(e){const r=canvas.getBoundingClientRect();return {time:clamp((e.clientX-r.left)/r.width*dur,0,dur),gain_db:clamp(12-(e.clientY-r.top)/r.height*72,-60,12)};}
  canvas.addEventListener("pointerdown",e=>{const r=canvas.getBoundingClientRect(),w=r.width,h=r.height;let best=-1,dist=12;pts.forEach((p,i)=>{const [x,y]=xy(p,w,h),d=Math.hypot(e.clientX-r.left-x,e.clientY-r.top-y);if(d<dist){dist=d;best=i;}});if(best<0){begin();dragPoint=point(e);pts.push(dragPoint);pts.sort((a,b)=>a.time-b.time);}else{begin();dragPoint=pts[best];}canvas.setPointerCapture?.(e.pointerId);draw();});canvas.addEventListener("pointermove",e=>{if(!dragPoint)return;Object.assign(dragPoint,point(e));pts.sort((a,b)=>a.time-b.time);draw();});canvas.addEventListener("pointerup",e=>{dragPoint=null;canvas.releasePointerCapture?.(e.pointerId);refresh();});canvas.addEventListener("contextmenu",e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),w=r.width,h=r.height;let best=-1,dist=12;pts.forEach((p,i)=>{const [x,y]=xy(p,w,h),d=Math.hypot(e.clientX-r.left-x,e.clientY-r.top-y);if(d<dist){dist=d;best=i;}});if(best>=0)commit(()=>pts.splice(best,1));});const ro=new ResizeObserver(resize);ro.observe(wrap);wrap._m3ssResizeObserver=ro;resize();
}

export function renderMaster(container, project, commit) {
  container.replaceChildren();const m=project.master,grid=el("div","m3ssv2-grid m3ssv2-grid-2");const gain=input("number",m.gain_db,-60,24,.1),mode=select(CHANNEL_MODES,m.channel_mode),norm=input("checkbox"),target=input("number",m.normalize.target_peak_dbfs,-60,0,.1);norm.checked=!!m.normalize.enabled;change(gain,"change",commit,x=>m.gain_db=clamp(x.value,-60,24));change(mode,"change",commit,x=>m.channel_mode=x.value);change(norm,"change",commit,x=>m.normalize.enabled=x.checked);change(target,"change",commit,x=>m.normalize.target_peak_dbfs=clamp(x.value,-60,0));grid.append(field("Master gain (dB)",gain),field("Channel mode",mode),field("Peak normalize",norm),field("Target peak dBFS",target));container.appendChild(grid);
}

export function renderTakes(container, meta, previewId, onPreview, showTakes, onToggle) {
  container.replaceChildren();const controls=el("div","m3ssv2-take-controls"),toggle=el("button","m3ssv2-button",showTakes?"Hide Take Lanes":"Show Take Lanes");toggle.type="button";toggle.onclick=onToggle;controls.appendChild(toggle);container.appendChild(controls);const list=el("div","m3ssv2-take-list");for(const t of meta?.takes||[]){const item=el("button",`m3ssv2-take-item${previewId===t.id?" is-active":""}`,`${t.name||t.id} · ${t.channels}ch · ${t.sample_rate} Hz · ${Number(t.duration).toFixed(2)} s`);item.type="button";item.onclick=()=>onPreview(t.id);list.appendChild(item);}container.appendChild(list);
}
