import { app } from "../../scripts/app.js";
import { createStudioWindow } from "./studio_shell.js";
import { hideNodeWidgets, installNodeSummary, getNodeWidget } from "./node_compact.js";
import { NODE_ID, EXTENSION_NAME, ensureStyles, clone, uid, nodeClass, el, button, input, select, field, clamp, fmtTime, clipDuration, clipEnd, timelineDuration, previewUrl, firstPreviewRef, extractMeta, defaultProject, normalizeProject, mainTrack, semanticOverlay, snapshot, parseSnapshot, splitClip, deleteTimelineRange } from "./audio_editor_core.js";
import { WaveformView } from "./audio_waveform.js";
import { renderTimeline } from "./audio_timeline.js";
import { renderInspector, renderEnvelope, renderMaster, renderTakes } from "./audio_panels.js";

function summaryFromMeta(meta){if(!meta?.takes?.length)return"Run once to load audio";return `${meta.takes.length} take${meta.takes.length===1?"":"s"} · ${Number(meta.rendered?.duration||meta.takes[0]?.duration||0).toFixed(1)} s · ${meta.bypass?"Bypassed":"Edited"}`;}

function openEditor(node, compactSummary){
  ensureStyles();const editWidget=getNodeWidget(node,"edit_json"),meta=node._m3ssV2Output;
  let cleanup=()=>{};const shell=createStudioWindow({title:"Music3 Semantic Studio Audio Editor",subtitle:meta?.takes?.length?`Phase 2 / V2 · ${summaryFromMeta(meta)} · backend render authoritative`:"Phase 2 / V2 · run once to load source audio",storageKey:"m3ss-audio-window",defaultWidth:1480,defaultHeight:900,minWidth:900,minHeight:600,onClose:()=>cleanup()});shell.window.classList.add("m3ssv2-dialog");
  if(!editWidget){shell.content.appendChild(el("div","m3ssv2-first-run","edit_json widget was not found. Restart ComfyUI and reload the workflow."));shell.mount();return;}
  if(!meta?.takes?.length){const box=el("div","m3ssv2-first-run","Run the workflow once to load source audio, then reopen the Audio Editor.");shell.content.appendChild(box);shell.mount();return;}
  let raw={};try{raw=JSON.parse(editWidget.value||"{}");}catch{raw={};}let project=normalizeProject(raw,meta);if(!project.project_id)project.project_id=uid("audio-project");let selectedId=mainTrack(project).clips[0]?.id||null,selection=null,previewId="rendered",activeInspector="clip",showTakes=false,viewInitialized=false;const history=[],future=[];

  const root=el("div","m3ssv2-root"),toolbar=el("div","m3ssv2-toolbar"),workspace=el("div","m3ssv2-workspace"),main=el("main","m3ssv2-main"),side=el("aside","m3ssv2-side"),footer=el("footer","m3ssv2-footer");root.append(toolbar,workspace,footer);workspace.append(main,side);shell.content.appendChild(root);
  const preview=select([{value:"rendered",label:"Rendered A"},...(meta.takes||[]).map(t=>({value:t.id,label:t.name||t.id}))],previewId),play=button("▶"),pause=button("Ⅱ"),stop=button("■"),undo=button("Undo"),redo=button("Redo"),fit=button("Fit"),zoom=input("range",28,8,120,1),time=el("span","m3ssv2-time","0:00.00"),takesToggle=button(`Takes (${meta.takes.length})`),renderState=el("span","m3ssv2-render-state","Rendered state");toolbar.append(field("Preview",preview),play,pause,stop,undo,redo,fit,field("Zoom",zoom),time,takesToggle,el("span","m3ssv2-wheel-hint","Wheel: zoom · Shift+Wheel: pan"),renderState);

  const waveWrap=el("section","m3ssv2-wave-wrap");main.appendChild(waveWrap);let wave=null;
  wave=new WaveformView(waveWrap,s=>{selection=s;selectionText.textContent=s?`Selection ${fmtTime(s.start)}–${fmtTime(s.end)}`:"No selection";},{onZoom:z=>{zoom.value=String(Math.round(z));project.view.zoom=z/28;},onScroll:s=>{project.view.scroll_seconds=s;}});wave.setSemanticSections(semanticOverlay(node));
  const timelineHead=el("div","m3ssv2-timeline-head");timelineHead.append(el("strong","","Main Comp"),el("span","m3ssv2-timeline-note","Drag clips to move · drag edges to trim"));main.appendChild(timelineHead);const timeline=el("div","m3ssv2-timeline");main.appendChild(timeline);
  const context=el("div","m3ssv2-contextbar"),split=button("Split @ Playhead"),del=button("Delete Selection"),dup=button("Duplicate"),cross=button("Crossfade Next"),useTake=button("Use Preview Take"),selectionText=el("span","m3ssv2-selection-text","No selection");context.append(split,del,dup,cross,useTake,selectionText);main.appendChild(context);

  const inspectorTabs=el("nav","m3ssv2-inspector-tabs"),inspectorBody=el("div","m3ssv2-inspector-body"),tabButtons=new Map();for(const [id,label] of [["clip","Clip"],["envelope","Envelope"],["master","Master"],["takes","Takes"]]){const b=button(label,"m3ssv2-inspector-tab");b.onclick=()=>{activeInspector=id;renderInspectorPanel();};tabButtons.set(id,b);inspectorTabs.appendChild(b);}side.append(inspectorTabs,inspectorBody);
  const status=el("div","m3ssv2-status"),actions=el("div","m3ssv2-footer-actions"),reset=button("Reset"),cancel=button("Cancel"),save=button("Save Edits","m3ssv2-button primary");actions.append(reset,cancel,save);footer.append(status,actions);

  const findClip=()=>mainTrack(project).clips.find(c=>c.id===selectedId)||null;
  function begin(){history.push(snapshot(project));if(history.length>100)history.shift();future.length=0;}
  function mark(renderDirty=true){if(renderDirty){renderState.textContent="Edits not rendered — Save, then Queue";renderState.classList.add("dirty");}renderAll();}
  function commit(fn){begin();fn();mark(true);}
  function restore(s){project=normalizeProject(parseSnapshot(s),meta);selectedId=mainTrack(project).clips.find(c=>c.id===selectedId)?.id||mainTrack(project).clips[0]?.id||null;renderState.textContent="Edits not rendered — Save, then Queue";renderState.classList.add("dirty");renderAll();}
  async function setPreview(id){previewId=id;preview.value=id;const entry=id==="rendered"?meta.rendered:meta.takes.find(t=>t.id===id),url=previewUrl(firstPreviewRef(entry));try{await wave.setSource(url);if(!viewInitialized){wave.setZoom(clamp((Number(project.view.zoom)||1)*28,8,120));wave.setScrollSeconds(project.view.scroll_seconds||0);viewInitialized=true;}}catch(e){alert(`Could not load audio preview: ${e}`);}renderInspectorPanel();}
  function cleanupInspector(){for(const child of inspectorBody.querySelectorAll(".m3ssv2-envelope-wrap"))child._m3ssResizeObserver?.disconnect?.();}
  function renderInspectorPanel(){cleanupInspector();for(const [id,b] of tabButtons)b.classList.toggle("is-active",id===activeInspector);if(activeInspector==="clip")renderInspector(inspectorBody,findClip(),meta,commit);else if(activeInspector==="envelope")renderEnvelope(inspectorBody,findClip(),commit,begin,()=>mark(true));else if(activeInspector==="master")renderMaster(inspectorBody,project,commit);else renderTakes(inspectorBody,meta,previewId,id=>setPreview(id),showTakes,()=>{showTakes=!showTakes;renderAll();});}
  function renderAll(){const dur=timelineDuration(project,meta);renderTimeline(timeline,project,meta,selectedId,id=>{selectedId=id;renderAll();},begin,()=>mark(true),dur,{showTakes});renderInspectorPanel();status.textContent=`${mainTrack(project).clips.length} clips · timeline ${fmtTime(dur)} · ${meta.takes.length} take(s)${meta.interactive_supported?"":" · batch preview: first item only"}`;undo.disabled=!history.length;redo.disabled=!future.length;takesToggle.classList.toggle("is-active",showTakes);takesToggle.textContent=`${showTakes?"Hide":"Show"} Takes (${meta.takes.length})`;useTake.disabled=meta.takes.length<=1||previewId==="rendered";}

  preview.onchange=()=>setPreview(preview.value);zoom.oninput=()=>wave.setZoom(Number(zoom.value));fit.onclick=()=>{wave.fit();project.view.zoom=wave.zoom/28;project.view.scroll_seconds=0;};play.onclick=()=>wave.play();pause.onclick=()=>wave.pause();stop.onclick=()=>wave.stop();takesToggle.onclick=()=>{showTakes=!showTakes;renderAll();};
  undo.onclick=()=>{if(!history.length)return;future.push(snapshot(project));restore(history.pop());};redo.onclick=()=>{if(!future.length)return;history.push(snapshot(project));restore(future.pop());};
  split.onclick=()=>{const track=mainTrack(project),t=wave.currentTime(),index=track.clips.findIndex(c=>c.id===selectedId),target=index>=0?index:track.clips.findIndex(c=>t>c.timeline_start&&t<clipEnd(c));if(target<0)return;const pieces=splitClip(track.clips[target],t);if(!pieces)return;commit(()=>{track.clips.splice(target,1,...pieces);selectedId=pieces[1].id;});};
  del.onclick=()=>{if(!selection||selection.end-selection.start<.001||previewId!=="rendered"){alert("Select a region on the Rendered preview first. Delete Selection is non-ripple and leaves a silence gap.");return;}commit(()=>{deleteTimelineRange(mainTrack(project),selection.start,selection.end);selectedId=mainTrack(project).clips[0]?.id||null;selection=null;wave.setSelection(null);});};
  dup.onclick=()=>{const c=findClip();if(!c)return;commit(()=>{const x=clone(c);x.id=uid("clip");x.timeline_start=clipEnd(c)+.05;mainTrack(project).clips.push(x);selectedId=x.id;});};
  cross.onclick=()=>{const track=mainTrack(project),c=findClip();if(!c)return;const ordered=[...track.clips].sort((a,b)=>a.timeline_start-b.timeline_start),i=ordered.findIndex(x=>x.id===c.id),next=ordered[i+1];if(!next)return;const d=Math.min(.5,clipDuration(c)/2,clipDuration(next)/2);if(d<=0)return;commit(()=>{if(clipEnd(c)-next.timeline_start<d)next.timeline_start=Math.max(0,clipEnd(c)-d);c.fade_out={duration:d,curve:"equal_power"};next.fade_in={duration:d,curve:"equal_power"};});};
  useTake.onclick=()=>{if(previewId==="rendered"){alert("Choose Take 1–4 in Preview first.");return;}const c=findClip();if(!c)return;const t=meta.takes.find(x=>x.id===previewId),max=Number(t?.duration)||clipDuration(c),old=clipDuration(c);commit(()=>{c.source_id=previewId;c.source_in=clamp(c.source_in,0,max);c.source_out=clamp(c.source_in+old,c.source_in+.01,max);});};
  reset.onclick=()=>{if(!confirm("Reset V2 edits to one full-length Take 1 clip?"))return;begin();project=defaultProject(meta);project.project_id=raw?.project_id||uid("audio-project");selectedId=mainTrack(project).clips[0]?.id||null;selection=null;wave.setSelection(null);mark(true);};
  save.onclick=()=>{const text=JSON.stringify(project);editWidget.value=text;editWidget.callback?.(text);compactSummary?.update(`${meta.takes.length} take${meta.takes.length===1?"":"s"} · ${mainTrack(project).clips.length} clips · edits pending Queue`);node.setDirtyCanvas?.(true,true);app.graph?.setDirtyCanvas?.(true,true);shell.close();};cancel.onclick=()=>shell.close();
  function keys(e){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo.click():undo.click();}if((e.ctrlKey||e.metaKey)&&e.key==="0"){e.preventDefault();fit.click();}if(e.code==="Space"&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){e.preventDefault();wave.audio.paused?play.click():pause.click();}}
  document.addEventListener("keydown",keys);const timer=setInterval(()=>time.textContent=fmtTime(wave.currentTime()),100);cleanup=()=>{clearInterval(timer);document.removeEventListener("keydown",keys);cleanupInspector();wave.destroy();};
  shell.mount();setPreview(previewId);renderAll();
}

function updateNodeMeta(node,message){const meta=extractMeta(message);if(!meta)return;node._m3ssV2Output=meta;node._m3ssV2Compact?.update(summaryFromMeta(meta));}

app.registerExtension({
  name:EXTENSION_NAME,
  async beforeRegisterNodeDef(nodeType,nodeData){if(nodeData?.name!==NODE_ID)return;const old=nodeType.prototype.onExecuted;nodeType.prototype.onExecuted=function(message){old?.apply(this,[message]);updateNodeMeta(this,message);};},
  async nodeCreated(node){if(nodeClass(node)!==NODE_ID||node._m3ssV2ButtonInstalled)return;node._m3ssV2ButtonInstalled=true;ensureStyles();hideNodeWidgets(node,["edit_json"]);const compact=installNodeSummary(node,{widgetName:"Editor Summary",text:summaryFromMeta(node._m3ssV2Output),minWidth:360});node._m3ssV2Compact=compact;const b=node.addWidget?.("button","Open Audio Editor",null,()=>openEditor(node,compact),{serialize:false});if(b){b.label="Open Audio Editor";b.serialize=false;}node.setSize?.([Math.max(node.size?.[0]||360,360),Math.min(Math.max(node.computeSize?.()[1]||170,170),300)]);},
  onNodeOutputsUpdated(outputs){for(const node of app.graph?._nodes||[]){if(nodeClass(node)!==NODE_ID)continue;const out=outputs?.[node.id]||outputs?.[String(node.id)];updateNodeMeta(node,out);}}
});
