import { app } from "../../scripts/app.js";
import { NODE_ID, EXTENSION_NAME, ensureStyles, clone, uid, nodeClass, getWidget, el, button, input, select, field, clamp, fmtTime, clipDuration, clipEnd, timelineDuration, previewUrl, firstPreviewRef, extractMeta, defaultProject, normalizeProject, mainTrack, semanticOverlay, snapshot, parseSnapshot, splitClip, deleteTimelineRange } from "./audio_editor_core.js";
import { WaveformView } from "./audio_waveform.js";
import { renderTimeline } from "./audio_timeline.js";
import { renderInspector, renderEnvelope, renderMaster } from "./audio_panels.js";

function openEditor(node){
  ensureStyles(); const editWidget=getWidget(node,"edit_json"), meta=node._m3ssV2Output;
  const overlay=el("div","m3ssv2-overlay"), dialog=el("section","m3ssv2-dialog"); overlay.appendChild(dialog);
  const head=el("header","m3ssv2-header"),titles=el("div");titles.append(el("h2","m3ssv2-title","Music3 Semantic Studio Audio Editor"),el("p","m3ssv2-subtitle","Phase 2 / V2 · non-destructive AUDIO editing · backend render is authoritative"));const closeBtn=button("×","m3ssv2-icon-button");head.append(titles,closeBtn);dialog.appendChild(head);
  if(!editWidget){dialog.appendChild(el("div","m3ssv2-empty","edit_json widget was not found. Restart ComfyUI and reload the workflow."));document.body.appendChild(overlay);closeBtn.onclick=()=>overlay.remove();return;}
  if(!meta?.takes?.length){dialog.appendChild(el("div","m3ssv2-first-run","Run the workflow once to load source audio, then reopen the Audio Editor."));const foot=el("footer","m3ssv2-footer");const ok=button("Close","m3ssv2-button primary");ok.onclick=()=>overlay.remove();foot.appendChild(ok);dialog.appendChild(foot);document.body.appendChild(overlay);closeBtn.onclick=()=>overlay.remove();return;}
  let raw={};try{raw=JSON.parse(editWidget.value||"{}");}catch{raw={};}let project=normalizeProject(raw,meta);if(!project.project_id)project.project_id=uid("audio-project");let selectedId=mainTrack(project).clips[0]?.id||null,selection=null,previewId="rendered";const history=[],future=[];

  const toolbar=el("div","m3ssv2-toolbar"),preview=select([{value:"rendered",label:"Rendered A"},...(meta.takes||[]).map(t=>({value:t.id,label:t.name||t.id}))],previewId),play=button("▶"),pause=button("Ⅱ"),stop=button("■"),undo=button("Undo"),redo=button("Redo"),zoom=input("range",28,8,120,1),time=el("span","m3ssv2-time","0:00.00"),renderState=el("span","m3ssv2-render-state","Rendered state");toolbar.append(field("Preview",preview),play,pause,stop,undo,redo,field("Zoom",zoom),time,renderState);dialog.appendChild(toolbar);
  const waveWrap=el("div","m3ssv2-wave-wrap");dialog.appendChild(waveWrap);const wave=new WaveformView(waveWrap,s=>{selection=s;selectionText.textContent=s?`Selection ${fmtTime(s.start)}–${fmtTime(s.end)}`:"No selection";});wave.setSemanticSections(semanticOverlay(node));
  const editbar=el("div","m3ssv2-editbar"),split=button("Split @ Playhead"),del=button("Delete Selection"),dup=button("Duplicate"),cross=button("Crossfade Next"),useTake=button("Use Preview Take"),selectionText=el("span","m3ssv2-selection-text","No selection");editbar.append(split,del,dup,cross,useTake,selectionText);dialog.appendChild(editbar);
  const timeline=el("div","m3ssv2-timeline");dialog.appendChild(timeline);
  const panels=el("div","m3ssv2-panels"),inspector=el("section","m3ssv2-panel"),envelope=el("section","m3ssv2-panel"),master=el("section","m3ssv2-panel");inspector.appendChild(el("h3","m3ssv2-panel-title","Clip Inspector"));envelope.appendChild(el("h3","m3ssv2-panel-title","Gain Envelope"));master.appendChild(el("h3","m3ssv2-panel-title","Master / Takes"));const inspectorBody=el("div"),envelopeBody=el("div"),masterBody=el("div");inspector.appendChild(inspectorBody);envelope.appendChild(envelopeBody);master.appendChild(masterBody);panels.append(inspector,envelope,master);dialog.appendChild(panels);
  const footer=el("footer","m3ssv2-footer"),status=el("div","m3ssv2-status"),actions=el("div","m3ssv2-footer-actions"),reset=button("Reset"),cancel=button("Cancel"),save=button("Save to Node","m3ssv2-button primary");actions.append(reset,cancel,save);footer.append(status,actions);dialog.appendChild(footer);

  const findClip=()=>mainTrack(project).clips.find(c=>c.id===selectedId)||null;
  function begin(){history.push(snapshot(project));if(history.length>100)history.shift();future.length=0;}
  function mark(){renderState.textContent="Edits not rendered — Save, then Queue";renderState.classList.add("dirty");renderAll();}
  function commit(fn){begin();fn();mark();}
  function restore(s){project=normalizeProject(parseSnapshot(s),meta);selectedId=mainTrack(project).clips.find(c=>c.id===selectedId)?.id||mainTrack(project).clips[0]?.id||null;renderState.textContent="Edits not rendered — Save, then Queue";renderState.classList.add("dirty");renderAll();}
  function setPreview(id){previewId=id;const entry=id==="rendered"?meta.rendered:meta.takes.find(t=>t.id===id),url=previewUrl(firstPreviewRef(entry));wave.setSource(url).catch(e=>alert(`Could not load audio preview: ${e}`));}
  function renderAll(){const dur=timelineDuration(project,meta);renderTimeline(timeline,project,meta,selectedId,id=>{selectedId=id;renderAll();},begin,mark,dur);renderInspector(inspectorBody,findClip(),meta,commit);renderEnvelope(envelopeBody,findClip(),commit,begin,mark);renderMaster(masterBody,project,meta,commit);status.textContent=`${mainTrack(project).clips.length} clips · timeline ${fmtTime(dur)} · ${meta.takes.length} take(s)${meta.interactive_supported?"":" · batch preview: first item only"}`;undo.disabled=!history.length;redo.disabled=!future.length;}

  preview.onchange=()=>setPreview(preview.value);zoom.oninput=()=>wave.setZoom(Number(zoom.value));play.onclick=()=>wave.play();pause.onclick=()=>wave.pause();stop.onclick=()=>wave.stop();
  undo.onclick=()=>{if(!history.length)return;future.push(snapshot(project));restore(history.pop());};redo.onclick=()=>{if(!future.length)return;history.push(snapshot(project));restore(future.pop());};
  split.onclick=()=>{const track=mainTrack(project),t=wave.currentTime(),index=track.clips.findIndex(c=>c.id===selectedId),target=index>=0?index:track.clips.findIndex(c=>t>c.timeline_start&&t<clipEnd(c));if(target<0)return;const pieces=splitClip(track.clips[target],t);if(!pieces)return;commit(()=>{track.clips.splice(target,1,...pieces);selectedId=pieces[1].id;});};
  del.onclick=()=>{if(!selection||selection.end-selection.start<.001||previewId!=="rendered"){alert("Select a region on the Rendered preview first. Delete Selection is non-ripple and leaves a silence gap.");return;}commit(()=>{deleteTimelineRange(mainTrack(project),selection.start,selection.end);selectedId=mainTrack(project).clips[0]?.id||null;selection=null;wave.setSelection(null);});};
  dup.onclick=()=>{const c=findClip();if(!c)return;commit(()=>{const x=clone(c);x.id=uid("clip");x.timeline_start=clipEnd(c)+.05;mainTrack(project).clips.push(x);selectedId=x.id;});};
  cross.onclick=()=>{const track=mainTrack(project),c=findClip();if(!c)return;const ordered=[...track.clips].sort((a,b)=>a.timeline_start-b.timeline_start),i=ordered.findIndex(x=>x.id===c.id),next=ordered[i+1];if(!next)return;const d=Math.min(.5,clipDuration(c)/2,clipDuration(next)/2);if(d<=0)return;commit(()=>{if(clipEnd(c)-next.timeline_start<d)next.timeline_start=Math.max(0,clipEnd(c)-d);c.fade_out={duration:d,curve:"equal_power"};next.fade_in={duration:d,curve:"equal_power"};});};
  useTake.onclick=()=>{if(previewId==="rendered"){alert("Choose Take 1–4 in Preview first.");return;}const c=findClip();if(!c)return;const t=meta.takes.find(x=>x.id===previewId),max=Number(t?.duration)||clipDuration(c),old=clipDuration(c);commit(()=>{c.source_id=previewId;c.source_in=clamp(c.source_in,0,max);c.source_out=clamp(c.source_in+old,c.source_in+.01,max);});};
  reset.onclick=()=>{if(!confirm("Reset V2 edits to one full-length Take 1 clip?"))return;begin();project=defaultProject(meta);project.project_id=raw?.project_id||uid("audio-project");selectedId=mainTrack(project).clips[0]?.id||null;mark();};
  save.onclick=()=>{const text=JSON.stringify(project);editWidget.value=text;editWidget.callback?.(text);node.setDirtyCanvas?.(true,true);app.graph?.setDirtyCanvas?.(true,true);close();};
  function close(){clearInterval(timer);wave.destroy();document.removeEventListener("keydown",keys);overlay.remove();}closeBtn.onclick=close;cancel.onclick=close;overlay.addEventListener("mousedown",e=>{if(e.target===overlay)close();});
  function keys(e){if(e.key==="Escape")close();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo.click():undo.click();}if(e.code==="Space"&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){e.preventDefault();wave.audio.paused?play.click():pause.click();}}
  document.addEventListener("keydown",keys);const timer=setInterval(()=>time.textContent=fmtTime(wave.currentTime()),100);document.body.appendChild(overlay);setPreview(previewId);renderAll();
}

app.registerExtension({name:EXTENSION_NAME,async beforeRegisterNodeDef(nodeType,nodeData){if(nodeData?.name!==NODE_ID)return;const old=nodeType.prototype.onExecuted;nodeType.prototype.onExecuted=function(message){old?.apply(this,[message]);const meta=extractMeta(message);if(meta)this._m3ssV2Output=meta;};},async nodeCreated(node){if(nodeClass(node)!==NODE_ID||node._m3ssV2ButtonInstalled)return;node._m3ssV2ButtonInstalled=true;ensureStyles();const b=node.addWidget?.("button","Open Audio Editor",null,()=>openEditor(node),{serialize:false});if(b)b.label="Open Audio Editor";node.setSize?.([Math.max(node.size?.[0]||340,340),node.size?.[1]||180]);},onNodeOutputsUpdated(outputs){for(const node of app.graph?._nodes||[]){if(nodeClass(node)!==NODE_ID)continue;const out=outputs?.[node.id]||outputs?.[String(node.id)],meta=extractMeta(out);if(meta)node._m3ssV2Output=meta;}}});
