import { clamp, clipDuration, clipEnd, el, fmtTime, mainTrack } from "./audio_editor_core.js";

export function renderTimeline(container, project, meta, selectedId, onSelect, begin, refresh, duration) {
  container.replaceChildren();
  const track=mainTrack(project), takeMap=new Map((meta?.takes||[]).map(t=>[t.id,t]));
  const header=el("div","m3ssv2-lane m3ssv2-lane-header"); header.append(el("div","m3ssv2-lane-label",track.name||"Main Comp"),el("div","m3ssv2-lane-body","Rendered clip plan")); container.appendChild(header);
  const lane=el("div","m3ssv2-lane"); lane.appendChild(el("div","m3ssv2-lane-label","Main Comp")); const body=el("div","m3ssv2-lane-body m3ssv2-clip-lane"); lane.appendChild(body); container.appendChild(lane);
  for(const clip of track.clips){const source=takeMap.get(clip.source_id), item=el("div",`m3ssv2-clip${clip.id===selectedId?" is-selected":""}${clip.muted?" is-muted":""}`);item.dataset.clipId=clip.id;item.style.left=`${clamp(clip.timeline_start/duration*100,0,100)}%`;item.style.width=`${Math.max(.5,clipDuration(clip)/duration*100)}%`;item.title=`${source?.name||clip.source_id} · ${fmtTime(clip.timeline_start)}–${fmtTime(clipEnd(clip))}`;item.appendChild(el("span","m3ssv2-clip-title",source?.name||clip.source_id));const left=el("span","m3ssv2-trim-handle left"),right=el("span","m3ssv2-trim-handle right");item.append(left,right);body.appendChild(item);item.addEventListener("pointerdown",e=>{if(e.target===left||e.target===right)return;onSelect(clip.id);const startX=e.clientX,startTime=Number(clip.timeline_start),rect=body.getBoundingClientRect();begin();item.setPointerCapture?.(e.pointerId);const move=ev=>{clip.timeline_start=Math.max(0,startTime+(ev.clientX-startX)/rect.width*duration);item.style.left=`${clip.timeline_start/duration*100}%`;};const up=ev=>{item.releasePointerCapture?.(ev.pointerId);item.removeEventListener("pointermove",move);item.removeEventListener("pointerup",up);refresh();};item.addEventListener("pointermove",move);item.addEventListener("pointerup",up);});
    const trim=(side,e)=>{e.stopPropagation();onSelect(clip.id);const src=takeMap.get(clip.source_id),max=Number(src?.duration)||duration,startX=e.clientX,rect=body.getBoundingClientRect(),old={source_in:clip.source_in,source_out:clip.source_out,timeline_start:clip.timeline_start};begin();item.setPointerCapture?.(e.pointerId);const move=ev=>{const delta=(ev.clientX-startX)/rect.width*duration;if(side==="left"){const next=clamp(old.source_in+delta,0,Number(old.source_out)-.01);const actual=next-old.source_in;clip.source_in=next;clip.timeline_start=Math.max(0,old.timeline_start+actual);}else clip.source_out=clamp(old.source_out+delta,Number(old.source_in)+.01,max);item.style.left=`${clip.timeline_start/duration*100}%`;item.style.width=`${Math.max(.5,clipDuration(clip)/duration*100)}%`;};const up=ev=>{item.releasePointerCapture?.(ev.pointerId);item.removeEventListener("pointermove",move);item.removeEventListener("pointerup",up);refresh();};item.addEventListener("pointermove",move);item.addEventListener("pointerup",up);};left.addEventListener("pointerdown",e=>trim("left",e));right.addEventListener("pointerdown",e=>trim("right",e));}
  for(const take of meta?.takes||[]){const row=el("div","m3ssv2-lane m3ssv2-take-lane");row.appendChild(el("div","m3ssv2-lane-label",take.name||take.id));const bar=el("div","m3ssv2-lane-body");const fill=el("div","m3ssv2-source-bar",`${take.channels}ch · ${take.sample_rate} Hz · ${Number(take.duration).toFixed(2)} s`);fill.style.width=`${Math.min(100,Number(take.duration)/duration*100)}%`;bar.appendChild(fill);row.appendChild(bar);container.appendChild(row);}
}
